---
# vim: foldmarker=[[[,]]]:foldmethod=marker

# Avoid version downgrade: https://travis-ci.org/debops/ansible-owncloud/builds/177238085#L1036
mariadb_server__packages_map:
  'mariadb': [ 'mysql-client-5.6' ]
