---

- hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: debops.etc_services
      etc_services__dependent_list:
        - '{{ rsyslog__etc_services__dependent_list }}'

    - role: debops.apt_preferences
      apt_preferences__dependent_list:
        - '{{ rsyslog__apt_preferences__dependent_list }}'

    - role: debops.ferm
      ferm__dependent_rules:
        - '{{ rsyslog__ferm__dependent_rules }}'

    - role: debops.logrotate
      logrotate__dependent_config:
        - '{{ rsyslog__logrotate__dependent_config }}'

    - role: 'ansible-rsyslog'

