---

- name: Configure tinc
  hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: ansible-tinc/env

    - role: debops.secret
      secret_directories: '{{ tinc__env_secret__directories }}'

    - role: debops.apt_preferences
      apt_preferences__dependent_list: '{{ tinc__apt_preferences__dependent_list }}'

    - role: debops.etc_services
      etc_services__dependent_list: '{{ tinc__env_etc_services__dependent_list }}'

    - role: debops.ferm
      ferm__dependent_rules: '{{ tinc__env_ferm__dependent_rules }}'

    - role: 'ansible-tinc'
