---

- hosts: 'placeholder_fqdn'
  become: True

  roles:

      # PostgreSQL requires configured PostgreSQL Server
    - role: 'debops.postgresql_server'

      # Install and configure PostgreSQL using cloned role
    - role: 'ansible-postgresql'

