---

- hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: debops.apt_preferences
      apt_preferences__dependent_list:
        - '{{ nginx_apt_preferences_dependent_list }}'

    - role: debops.ferm
      ferm__dependent_rules:
        - '{{ nginx_ferm_dependent_rules }}'

    - role: debops.nginx
      nginx_servers: '{{ preseed__nginx__servers }}'

    - role: ansible-preseed

