---

- hosts: 'placeholder_fqdn'
  become: True

  roles:


    - role: debops.postfix/env

    - role: ansible-opendkim/env

    - role: debops.secret
      secret__directories:
        - '{{ opendkim__secret__directories }}'
        - '{{ postfix__secret__directories }}'

    - role: debops.apt_preferences
      apt_preferences__dependent_list:
        - '{{ unbound__apt_preferences__dependent_list }}'

    - role: debops.etc_services
      etc_services__dependent_list:
        - '{{ unbound__etc_services__dependent_list }}'

    - role: debops.unbound

    - role: debops.postfix
      postfix__dependent_maincf:
        - role: 'opendkim'
          config: '{{ opendkim__postfix__dependent_maincf }}'

    - role: ansible-opendkim
