---

- hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: debops.postfix/env

    - role: ansible-opendkim/env

    - role: debops.secret
      secret__directories:
        - '{{ opendkim__secret__directories }}'
        - '{{ postfix__secret__directories }}'

    - role: debops.postfix

    - role: ansible-opendkim
