---

- hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: debops.apt_preferences
      apt_preferences__dependent_list:
        - '{{ golang__apt_preferences__dependent_list }}'

    - role: ansible-golang
