---

- name: Manage Elasticsearch server
  hosts: [ 'debops_service_elasticsearch_master',
           'debops_service_elasticsearch_workhorse',
           'debops_service_elasticsearch_coordinator',
           'debops_service_elasticsearch_loadbalancer' ]
  become: True

  roles:

    - role: debops.etc_services
      etc_services__dependent_list:
        - '{{ elasticsearch__etc_services__dependent_list }}'

    - role: debops.ferm
      ferm__dependent_rules:
        - '{{ elasticsearch__ferm__dependent_rules }}'

    - role: debops.java

    - role: ansible-elasticsearch
