---

- hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: 'ansible-pki/env'

    - role: debops.secret
      secret_directories:
        - '{{ pki_env_secret_directories }}'

    - role: 'ansible-pki'

