---

postgresql_roles:

  - role: 'travis_test'
    flags: [ 'NOLOGIN' ]

  - role: 'travis'

postgresql_groups:

  - roles: [ 'travis' ]
    groups: [ 'travis_test' ]
    database: 'travis_test'

postgresql_databases:

  - name: 'travis_test'
    owner: 'travis_test'

postgresql_pgpass:

  - owner: 'travis'


