---

postgresql__roles:

  - role: 'travis_test'
    flags: [ 'NOLOGIN' ]

  - role: 'travis'

postgresql__groups:

  - roles: [ 'travis' ]
    groups: [ 'travis_test' ]
    database: 'travis_test'

postgresql__databases:

  - name: 'travis_test'
    owner: 'travis_test'

postgresql__extensions:

  - database: 'travis_test'
    extension: 'pg_trgm'

postgresql__pgpass:

  - owner: 'travis'


