---

- name: Manage Kibana service
  hosts: [ 'debops_service_kibana' ]
  become: True

  roles:

    - role: ansible-kibana/env

    - role: debops.secret
      secret__directories:
        - '{{ kibana__secret__directories }}'

    - role: debops.apt_preferences
      apt_preferences__dependent_list:
        - '{{ elastic_co__apt_preferences__dependent_list }}'
        - '{{ nginx__apt_preferences__dependent_list }}'

    - role: debops.etc_services
      etc_services__dependent_list:
        - '{{ kibana__etc_services__dependent_list }}'

    - role: debops.ferm
      ferm__dependent_rules:
        - '{{ nginx__ferm__dependent_rules }}'

    - role: debops.nginx
      nginx__dependent_servers:
        - '{{ kibana__nginx__dependent_servers }}'
      nginx__dependent_upstreams:
        - '{{ kibana__nginx__dependent_upstreams }}'

    - role: debops.elastic_co
      elastic_co__dependent_packages:
        - '{{ kibana__elastic_co__dependent_packages }}'

    - role: ansible-kibana
