---

- hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: 'debops.dhparam'

- include: '../../common-ansible-playbooks/pki.yml'

- hosts: 'placeholder_fqdn'
  become: True

  roles:

      # LDAP client is configured by debops.auth
    - role: 'debops.auth'

      # Install and configure slapd using cloned role
    - role: 'ansible-slapd'

