---

unbound__server:

  - name: 'interface'
    value: '0.0.0.0'
    comment: |
      IPv6 on Travis-CI seems to not work:
      Restarting recursive DNS server unbound...
      unbound[12428:0] debug: failed address ::1 port 53

  - verbosity: 1

  - name: 'extended-statistics'
    value: True

unbound__zones:

  - name: 'test-zone'
    zone: 'nat.example.net'
    revdns: '192.168.0.0/20'
    nameserver: '8.8.4.4'
