---

- hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: 'debops.pki/env'

    - role: debops.secret
      secret_directories:
        - '{{ pki_env_secret_directories }}'

    - role: 'debops.pki'


- hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: debops.etc_services
      etc_services__dependent_list:
        - '{{ mosquitto__etc_services__dependent_list }}'

    - role: debops.tcpwrappers
      tcpwrappers__dependent_allow:
        - '{{ mosquitto__tcpwrappers__dependent_allow }}'

    - role: debops.ferm
      ferm__dependent_rules:
        - '{{ mosquitto__ferm__dependent_rules }}'

    - role: ansible-mosquitto
