---

postgresql_server__delegate_to: 'localhost'

# Debug PostgreSQL issues
#postgresql_server__hba_local:
#
#  - comment:  'Access through local UNIX socket with password'
#    type:     'local'
#    database: 'samerole'
#    user:     'all'
#    method:   'md5'
#
#  - comment:  'Access from localhost via IPv6'
#    type:     'host'
#    database: 'samerole'
#    user:     'all'
#    address:  '::1/128'
#    method:   'md5'
#
#  - comment:  'Access from localhost via IPv4'
#    type:     'host'
#    database: 'samerole'
#    user:     'all'
#    address:  '127.0.0.1/32'
#    method:   'md5'
#
#  - comment:  'Access from localhost'
#    type:     'host'
#    database: 'samerole'
#    user:     'all'
#    address:  'localhost'
#    method:   'md5'
