---

- include: '../../common-ansible-playbooks/pki.yml'

- hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: debops.etc_aliases/env

    - role: ansible-postfix/env

    - role: debops.secret
      secret__directories:
        - '{{ etc_aliases__secret__directories }}'
        - '{{ postfix__secret__directories }}'

    - role: debops.ferm
      ferm__dependent_rules:
        - '{{ postfix__ferm__dependent_rules }}'

    - role: debops.etc_aliases

      # Install and configure Postfix using cloned role
    - role: 'ansible-postfix'

