---

# Don't try to change default user account, it seems that Ubuntu Precise
# doesn't like it
users__admin_accounts: []

# Make sure that audio system group exists
users__groups:

  - name: 'audio'
    group: 'audio'
    system: 'yes'

# User accounts on the test host
users__host_accounts:

  - name: 'testuser'
    home: '/tmp/testuser'
    groups: [ 'audio' ]

    # The default shell is bash and dotfiles are disabled by default.
    shell: '/bin/zsh'
    dotfiles_enabled: True
    sshkeys:
      - 'ssh-rsa 000000 test'

