---

- hosts: 'placeholder_fqdn'
  become: True

  roles:

      # Create required system users
    - role: 'debops.auth'

      # Configure SSL certificates
    - role: 'debops.pki'

      # Configure NodeJS
    - role: 'debops.nodejs'

      # Install and configure rails app using cloned role
    - role: 'ansible-rails_deploy'

