---

- include: '../../common-ansible-playbooks/pki.yml'

- hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: debops.apt_preferences
      apt_preferences__dependent_list:
        - '{{ postgresql_server__apt_preferences__dependent_list }}'

    - role: debops.etc_services
      etc_services__dependent_list:
        - '{{ postgresql_server__etc_services__dependent_list }}'

    - role: debops.ferm
      ferm__dependent_rules:
        - '{{ postgresql_server__ferm__dependent_rules }}'

    - role: 'debops.postgresql_server'

- hosts: 'placeholder_fqdn'
  become: True

  roles:

      # Create required system users
    - role: 'debops.auth'

      # Configure NodeJS
    - role: 'debops.nodejs'

      # Install and configure rails app using cloned role
    - role: 'ansible-rails_deploy'

