---

- name: Configure ifupdown
  hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: debops.ifupdown/env

    - role: debops.ferm
      ferm_dependent_rules:
        - '{{ ifupdown__env_ferm__dependent_rules }}'

    - role: debops.ifupdown


- name: Configure radvd
  hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: ansible-radvd
