---

- hosts: 'placeholder_fqdn'
  sudo: True

  roles:
      # Nginx requires configured SSL certificates
    - role: 'debops.pki'

      # Install and configure nginx using cloned role
    - role: 'ansible-nginx'

