---

- name: Manage monit service
  hosts: 'placeholder_fqdn'
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.apt_preferences
      apt_preferences__dependent_list:
        - '{{ monit__apt_preferences__dependent_list }}'

    - role: debops.etc_services
      etc_services__dependent_list:
        - '{{ monit__etc_services__dependent_list }}'

    - role: ansible-monit
