---

- hosts: 'placeholder_fqdn'
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.postfix

- hosts: 'placeholder_fqdn'
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    # Disable the role for now
    #- role: debops-contrib.apparmor

    - role: debops.apt_preferences
      apt_preferences__dependent_list:
        - '{{ lxc__apt_preferences__dependent_list }}'

    - role: debops.ferm
      ferm__forward: '{{ lxc__ferm__forward|bool }}'
      ferm__dependent_rules:
        - '{{ lxc__ferm__dependent_rules }}'

    - role: 'ansible-lxc'
