---

- hosts: 'placeholder_fqdn'
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.postfix

- hosts: 'placeholder_fqdn'
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    # Error on Travis-CI:
    # install 'debootstrap' 'lxc' 'lxc-templates' 'libcgmanager0'' \
    # failed: AppArmor parser error for /etc/apparmor.d/lxc-containers \
    # in /etc/apparmor.d/lxc-containers at line 5: Could not open 'tunables/global'

    #- role: debops-contrib.apparmor

    - role: debops.apt_preferences
      apt_preferences__dependent_list:
        - '{{ lxc__apt_preferences__dependent_list }}'

    - role: debops.ferm
      ferm__forward: '{{ lxc__ferm__forward|bool }}'
      ferm__dependent_rules:
        - '{{ lxc__ferm__dependent_rules }}'

    - role: 'ansible-lxc'
