---

- hosts: 'placeholder_fqdn'
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.etc_aliases/env

    - role: debops.postfix/env

    - role: debops.secret
      secret__directories:
        - '{{ etc_aliases__secret__directories }}'
        - '{{ postfix__secret__directories }}'

    - role: debops.ferm
      ferm__dependent_rules:
        - '{{ postfix__ferm__dependent_rules }}'

    - role: debops.etc_aliases

    - role: debops.postfix

- hosts: 'placeholder_fqdn'
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops-contrib.apparmor

    - role: debops.apt_preferences
      apt_preferences__dependent_list:
        - '{{ lxc__apt_preferences__dependent_list }}'

    - role: debops.ferm
      ferm__forward: '{{ lxc__ferm__forward|bool }}'
      ferm__dependent_rules:
        - '{{ lxc__ferm__dependent_rules }}'

    - role: 'ansible-lxc'
