---

- hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: 'debops.apt_preferences'
      apt_preferences__dependent_list:
        - '{{ apt_install__apt_preferences__dependent_list }}'

    - role: 'ansible-apt_install'

