---

- hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: 'debops.ferm'
      ferm__dependent_rules:
        - '{{ libvirtd_qemu__ferm__dependent_rules }}'

    - role: 'ansible-libvirtd_qemu'

