---

# Set APT pin for nginx packages to be installed from precise-updates
apt_preferences_list:
  - package: 'nginx nginx-*'
    pin: 'release a={{ ansible_distribution_release }}-updates'

# Check meta/main.yml to see how to use it as a dependency.
