---

- hosts: 'placeholder_fqdn'
  become: True

  roles:

    ## Run required role from the `common.yml` playbook to ensure that backports in Ubuntu are enabled.
    - role: 'debops.apt'

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ nginx_apt_preferences_dependent_list }}'
        - '{{ owncloud__apt_preferences__dependent_list }}'

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm__dependent_rules:
        - '{{ nginx_ferm_dependent_rules }}'

    - role: debops.mariadb
      tags: [ 'role::mariadb' ]
      mariadb_users:
        - database: '{{ owncloud_database_map[owncloud_database].dbname }}'
          user: '{{ owncloud_database_map[owncloud_database].dbuser }}'
          password: '{{ owncloud_database_map[owncloud_database].dbpass }}'
      when: (owncloud_database == 'mariadb')

    - role: debops.php5
      tags: [ 'role::php5' ]
      php5_pools:
        - '{{ owncloud__php5__pool }}'

    - role: debops.nginx
      tags: [ 'role::nginx' ]
      nginx_dependent_servers:
        - '{{ owncloud__nginx__servers }}'
      nginx_dependent_upstreams:
        - '{{ owncloud__nginx__upstream_php5 }}'

    - role: 'ansible-owncloud'

