---

- hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: 'debops.apt_preferences'
      apt_preferences__dependent_list:
        - '{{ libvirtd__apt_preferences__dependent_list }}'

    - role: 'debops.ferm'
      ferm__dependent_rules:
        - '{{ libvirtd__ferm__dependent_rules }}'

    - role: 'ansible-libvirtd'

