---

- name: Configure Mailman
  hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: debops.postfix/env

    - role: 'debops.pki/env'

    - role: debops.secret
      secret_directories:
        - '{{ pki_env_secret_directories }}'
        - '{{ postfix__secret__directories }}'

    - role: debops.pki

    - role: debops.fcgiwrap
      fcgiwrap__instances:
        - '{{ mailman__fcgiwrap__instance }}'

    - role: debops.unattended_upgrades
      unattended_upgrades__dependent_blacklist: '{{ mailman__unattended_upgrades__dependent_blacklist }}'

    - role: debops.apt_preferences
      apt_preferences_dependent_list:
        - '{{ mailman__apt_preferences__dependent_list }}'
        - '{{ nginx__apt_preferences__dependent_list }}'

    - role: debops.ferm
      ferm_dependent_rules:
        - '{{ postfix__ferm__dependent_rules }}'
        - '{{ nginx__ferm__dependent_rules }}'

    - role: debops.postfix
      postfix__dependent_maincf:
        - role: 'mailman'
          config: '{{ mailman__postfix__dependent_maincf }}'

    - role: debops.nginx
      nginx_servers: '{{ mailman__nginx__servers }}'

    - role: ansible-mailman

