---

- name: Manage Public Key Infrastructure
  hosts: 'all'
  become: True

  roles:

    - role: debops.pki/env

    - role: debops.secret
      secret_directories:
        - '{{ pki_env_secret_directories }}'

    - role: debops.pki

