---

- hosts: 'placeholder_fqdn'
  sudo: True

  roles:

    - role: 'debops.mariadb_server'
    - role: 'debops.snmpd'

- hosts: 'placeholder_fqdn'
  sudo: True

  roles:

      # Install and configure LibreNMS using cloned role
    - role: 'ansible-librenms'

