---

- hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: 'debops.mariadb_server'
    - role: 'debops.snmpd'

- hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: debops.php/env

    - role: debops.apt_preferences
      apt_preferences__dependent_list:
        - '{{ php__apt_preferences__dependent_list }}'
        - '{{ nginx__apt_preferences__dependent_list }}'

    - role: debops.logrotate
      logrotate__dependent_config:
        - '{{ php__logrotate__dependent_config }}'
        - '{{ librenms__logrotate__dependent_config }}'

    - role: debops.ferm
      ferm__dependent_rules:
        - '{{ nginx__ferm__dependent_rules }}'

    - role: debops.php
      php__dependent_packages:
        - '{{ librenms__php__dependent_packages }}'
      php__dependent_pools:
        - '{{ librenms__php__dependent_pools }}'

    - role: debops.nginx
      nginx__dependent_servers:
        - '{{ librenms__nginx__dependent_servers }}'
      nginx__dependent_upstreams:
        - '{{ librenms__nginx__dependent_upstreams }}'

    - role: debops.mariadb
      mariadb__dependent_users:
        - '{{ librenms__mariadb__dependent_users }}'

      # Install and configure LibreNMS using cloned role
    - role: 'ansible-librenms'
