---

- hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: debops.apt_preferences
      apt_preferences__dependent_list:
        - '{{ elastic_co__apt_preferences__dependent_list }}'

    - role: 'ansible-elastic_co'
