---

# Install 1 or more packages.
apt__packages: ['vim']

# Use specific mirror for Precise Pangolin as configured by travis-ci.org.
apt__default_mirrors: []
apt__mirrors: [ 'http://us.archive.ubuntu.com/ubuntu/' ]

