---

- hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: 'debops.apt_preferences'
      apt_preferences__dependent_list:
        - '{{ unbound__apt_preferences__dependent_list }}'

    - role: 'debops.etc_services'
      etc_services__dependent_list:
        - '{{ unbound__etc_services__dependent_list }}'

    - role: 'ansible-unbound'

