---

# Monit can be slightly faster during testing
monit__check_interval: '10'
monit__start_delay: '0'

monit__config:

  - name: 'sshd'
    state: 'present'

  - name: 'mysql'
    state: 'present'

  - name: 'cron'
    state: 'present'

  - name: 'rsyslog'
    state: 'present'
